services:
    mercari-bot:
        image: ghcr.io/kimata/mercari-bot:latest@sha256:011fe255a8e3a4391896f4dc6bb1c5d4bd8d20340a79da95db08f10ec84f1e7b
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/mercari-bot/config.yaml:ro
            - ./data:/opt/mercari-bot/data
