services:
    mercari-bot:
        image: ghcr.io/kimata/mercari-bot:latest@sha256:02e434e13f96da6ef49771551a513ba571555663a740b039e252a63bc85f2d81
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/mercari-bot/config.yaml:ro
            - ./data:/opt/mercari-bot/data
