services:
    mercari-bot:
        image: ghcr.io/kimata/mercari-bot:latest@sha256:add22ae5f36ee40b907a7b4b4ac235d5b23b78e924de177669c4603d3c2f9ea4
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/mercari-bot/config.yaml:ro
            - ./data:/opt/mercari-bot/data
